server:
  port: 9999

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.springframework.security: INFO

spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5 # 若为HTML5则校验很严格，很麻烦
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seclogin?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: cj
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
