server:
  port: 9999

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.springframework.security: INFO

spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/seclogin?useUnicode=true&characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
    username: cj
    password: 123

mybatis:
  configuration:
    map-underscore-to-camel-case: true   #开启驼峰命名转换
